### ISSUE TITLE
Consider adding incentive program to "running a full node" documentation

### ISSUE THREAD

**Issue by jlopp** [bitcoin/bitcoin.org#762]
There's a good write-up for how to enable your full node for Bitnodes' incentive program here: https://www.reddit.com/r/Bitcoin/comments/2wrmes/how_to_set_up_an_incentivized_node_in_ubuntu/

**Comment by harding** [comment]
I don't like this idea.

1. (Right now) If I read the [incentive page](https://getaddr.bitnodes.io/nodes/incentive/) correctly, Addy Yeow is currently only offering a total incentive of $10 a week no matter how many nodes sign up.  The $10 is paid out lottery style, so only one person gets it, but the actual value of the incentive is $10 / [number of participating nodes, min 100] per node per week.  I have a hard time believing an incentive that starts at $0.10 per week (and goes down from there) can be effective at accomplishing anything, except apparently getting some people on Reddit to jump through hoops.

2. (Long-term) If the value of the incentive is increased, it will likely attract people trying to scam the incentive program by creating nodes designed to receive the incentive rather than help the network.  These could be fake nodes that don't really support the network, or they could be real nodes run on hacked computers that earn Bitcoin more bad press and also make it hard for P2P SPV clients to have a reasonable chance of connecting to an honestly-run node, thus making attacks easier.

**Comment by jlopp** [comment]
I don't think it will incentivize people to run nodes who weren't going to anyway, it's just a plus.

After reviewing the metrics that Addy uses to judge the honesty and helpfulness of nodes it seems it would be quite difficult to run an unhelpful / fake node that actually qualifies for the payout with a Peer Index score of > 0.8. As for the botnet stuff, the same thing happened with mining back in the day but it didn't seem to have a negative impact on the ecosystem...

**Comment by harding** [comment]
> I don't think it will incentivize people to run nodes

Then I don't see the point.

> it seems it would be quite difficult to run an unhelpful / fake node that actually qualifies for the payout with a Peer Index score of > 0.8

It looks easy to me:

1. Get a bunch of IP addresses.  The site seems to track nodes with IPv6 addresses, and getting IPv6 addresses is easy

2. Setup a full node that operates on all those IP addresses

3. Setup a web server that returns a different payout address for each IP address

> As for the botnet stuff, the same thing happened with mining back in the day but it didn't seem to have a negative impact on the ecosystem...

If botnet mining was still effective, we'd be spending a lot of developer time trying to make it ineffective.  Why?  Because either we stop people from abusing our system, or people who make security software will stop people from *using* our system.

For years now, my home ISP has blocked port 25 (SMTP) because many botnets are used to send spam.  If it becomes common for botnets to run full nodes, we'll likely see port 8333 blocked as well.

---

Anyway, that's all I care to say.  Other people are welcome to comment, of course, and to submit a pull request adding these instructions.  (But, fair warning, I'll probably vote against merging those instructions.)

**Comment by jlopp** [comment]
Alrighty; no big deal
