### ISSUE TITLE
Running a full node on Windows 8.1

### ISSUE THREAD

**Issue by chickenwingspicy** [bitcoin/bitcoin.org#763]
Hi, I'm running a full node (~20 connections) with Bitcoin Core Version v0.10.0rc1 (64-Bit) on Windows 8.1 and willing to help out!

**Comment by harding** [comment]
@chickenwingspicy excellent, thanks!  Here's what we need:

* Uninstall Bitcoin Core so that you can reinstall it fresh

* If you need to, install some screenshot software.  (I don't use Windows, so I don't have any suggestions, but I'm sure there are a ton of programs that take simple screeenshots.)

* Open the [Win 7 instructions](https://bitcoin.org/en/full-node#windows-7) and try to follow it.  Anywhere the instructions are different for Win 8.1, make a detailed note describing the change.

* If anything on Win 8.1 looks different than in the screenshots from 7, or if there are any new pop-ups or whatever, take a screenshot of those.  I think screenshots of security prompts are particularly useful, since they tend to vary a lot between OSes.  It never hurts to take too many screenshots and then delete the ones you don't need later.

* Make sure you also follow the instructions for "Start Your Node At Login" in the Win 7 section and make notes/take screenshots of anything that's different.

After you have all your screenshots and notes, put them somewhere I can access them.  I suggest a public Google doc, but you can also email dave@dtrt.org.  (If you have lots of images, send multiple emails with up to 5 images per email.)

I'll review the notes, ask you any follow-up questions, and write an update for the doc.  When I'm done, I'll create a pull request here on GitHub that you can review and test.

Let me know if you have any questions, and thanks again!
