### ISSUE TITLE
Setup of a full node should be automated

### ISSUE THREAD

**Issue by janschejbal** [bitcoin/bitcoin.org#768]
The how-to guide for setting up a full node is nice, but every step after the "apt-get install bitcoind" can and should be automated, either in the official ppa or a separate one:

* Create locked account
* Create directory structure
* Create bitcoin.conf with random password and correct permissions
* Configure logging to /var/log
* Set up log rotation (this is not mentioned in the guide, but should be)
* Create init.d or upstart file (ask user if the service should be configured to autostart)

Bonus points for setting up an AppArmor profile to improve security and autodetecting Tor running on the same machine. The tor package can probably be used as a template - it includes logrotate and AppArmor.

**Comment by harding** [comment]
@janschejbal I agree that would be awesome, and it would be great if you're willing to help!  The Ubuntu packaging files are all in the [Bitcoin Core repository](https://github.com/bitcoin/bitcoin) (in the contrib/ directory, I believe) and [this issue](https://github.com/bitcoin/bitcoin/issues/4124) describes some of the things that need to be done, as well as possible concerns.

This repository here is just for Bitcoin.org content, so I'm going to close the issue, but thanks for suggesting it!

Also, regarding one of your bullet points:

> Set up log rotation (this is not mentioned in the guide, but should be)

I just wanted to let you know that Bitcoin Core trims its own log on startup by default, which is why it's not in the guide.
