### ISSUE TITLE
undocumented RPC calls

### ISSUE THREAD

**Issue by jlopp** [bitcoin/bitcoin.org#836]
There are some RPC calls that appear to be undocumented:

invalidateblock
reconsiderblock
setmocktime

**Comment by gmaxwell** [comment]
hese RPCs are for diagnostic purposes and not intended for general supported use and are explicitly hidden in the software.

**Comment by harding** [comment]
@jlopp that's deliberate.  They're in the hidden RPC category in Bitcoin Core, so they aren't listed when you run `bitcoin-cli help`.  If the core devs think they should be hidden, I don't think we should show them.  (Especially since they're pretty much useless for anything besides writing unit tests.)

However, let me know if you disagree.  Also maybe let the core devs know if you think they shouldn't be hidden.

**Comment by jlopp** [comment]
The reason that I came across these undocumented calls was that I need to test how my service manages block chain forks. I ended up on this post: http://bitcoin.stackexchange.com/questions/36649/testing-blockchain-forks

Is there an alternate recommended way to test block chain forking?

**Comment by harding** [comment]
@jlopp here's how I once recommended testing them: http://bitcoin.stackexchange.com/questions/32664/bitcoind-confirmations-during-fork/32666#32666

**Comment by jlopp** [comment]
Great, thanks. I don't suppose you know of anyone who has released a node network simulator that spools up several regtest nodes and has them generate realistic traffic? If not, I may look into it myself as it would be a huge help for speeding up the testing of my service.

**Comment by harding** [comment]
@jlopp I don't know of any such software, but if you write it and release it as open source, please send me a link so I can add it to the docs (somewhere; I'm not sure where yet).
