### ISSUE TITLE
Mac OS X Instructions

### ISSUE THREAD

**Issue by pipgras** [bitcoin/bitcoin.org#905]
Can I get the instructions for setting up a mac full node. I'm trying to setup P2Pool

**Comment by harding** [comment]
@pipgras sorry, no one has volunteered to write BItcoin Core installation instructions for Mac, but I suggest you start by downloading the DMG from the [Download page](https://bitcoin.org/en/download).  If you need still need help, try the resources listed on the [Community page](https://bitcoin.org/en/community).

I'm going to close this issue now because we don't usually provide support here.  Best of luck!
